syntax = "proto3";

package user.v1;

import "buf/validate/validate.proto";

option go_package = "github.com/auroban/gochat-be/user-service/proto;user";

service UserService {
    rpc CreateUser(CreateUserRequest) returns (CreateUserResponse);
    rpc GetUser(GetUserRequest) returns (GetUserResponse);
}

enum UserStatus {
    USER_STATUS_UNSPECIFIED = 0;
    USER_STATUS_ACTIVE = 1;
    USER_STATUS_INACTIVE = 2;
    USER_STATUS_SUSPENDED = 3;
}

message CreateUserRequest {
    string username = 1 [(buf.validate.field).string = {
        min_len: 3,
        max_len: 32
    }];
    string email = 2 [(buf.validate.field).string.email = true];
    string password = 3 [(buf.validate.field).string.min_len = 8];
    string display_name = 4 [(buf.validate.field).string.min_len = 1];
    string auth_provider = 5 [(buf.validate.field).string.min_len = 1];
    string type = 6 [(buf.validate.field).string.min_len = 1];
}

message CreateUserResponse {
    string username = 1;
    string email = 2;
    string display_name = 3;
    string auth_provider = 4;
    string type = 5;
    UserStatus status = 6;
}

message GetUserRequest {
    option (buf.validate.message).cel = {
        id: "username_or_email_required"
        message: "either username or email must be present"
        expression: "this.username != '' || this.email != ''"
    };
    string username = 1;
    string email = 2;
}

message GetUserResponse {
    string username = 1;
    string email = 2;
    string display_name = 3;
    string auth_provider = 4;
    string type = 5;
    UserStatus status = 6;
}