// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: profile/v1/profile.proto

package profile

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProfileStatus int32

const (
	ProfileStatus_PROFILE_STATUS_UNSPECIFIED ProfileStatus = 0
	ProfileStatus_PROFILE_STATUS_ACTIVE      ProfileStatus = 1
	ProfileStatus_PROFILE_STATUS_INACTIVE    ProfileStatus = 2
	ProfileStatus_PROFILE_STATUS_SUSPENDED   ProfileStatus = 3
)

// Enum value maps for ProfileStatus.
var (
	ProfileStatus_name = map[int32]string{
		0: "PROFILE_STATUS_UNSPECIFIED",
		1: "PROFILE_STATUS_ACTIVE",
		2: "PROFILE_STATUS_INACTIVE",
		3: "PROFILE_STATUS_SUSPENDED",
	}
	ProfileStatus_value = map[string]int32{
		"PROFILE_STATUS_UNSPECIFIED": 0,
		"PROFILE_STATUS_ACTIVE":      1,
		"PROFILE_STATUS_INACTIVE":    2,
		"PROFILE_STATUS_SUSPENDED":   3,
	}
)

func (x ProfileStatus) Enum() *ProfileStatus {
	p := new(ProfileStatus)
	*p = x
	return p
}

func (x ProfileStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProfileStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_profile_v1_profile_proto_enumTypes[0].Descriptor()
}

func (ProfileStatus) Type() protoreflect.EnumType {
	return &file_profile_v1_profile_proto_enumTypes[0]
}

func (x ProfileStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProfileStatus.Descriptor instead.
func (ProfileStatus) EnumDescriptor() ([]byte, []int) {
	return file_profile_v1_profile_proto_rawDescGZIP(), []int{0}
}

type CreateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	DisplayName   string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AuthProvider  string                 `protobuf:"bytes,5,opt,name=auth_provider,json=authProvider,proto3" json:"auth_provider,omitempty"`
	Type          string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileRequest) Reset() {
	*x = CreateProfileRequest{}
	mi := &file_profile_v1_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileRequest) ProtoMessage() {}

func (x *CreateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateProfileRequest) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProfileRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateProfileRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateProfileRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateProfileRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreateProfileRequest) GetAuthProvider() string {
	if x != nil {
		return x.AuthProvider
	}
	return ""
}

func (x *CreateProfileRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type CreateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AuthProvider  string                 `protobuf:"bytes,4,opt,name=auth_provider,json=authProvider,proto3" json:"auth_provider,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Status        ProfileStatus          `protobuf:"varint,6,opt,name=status,proto3,enum=profile.v1.ProfileStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileResponse) Reset() {
	*x = CreateProfileResponse{}
	mi := &file_profile_v1_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileResponse) ProtoMessage() {}

func (x *CreateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileResponse.ProtoReflect.Descriptor instead.
func (*CreateProfileResponse) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProfileResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateProfileResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateProfileResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreateProfileResponse) GetAuthProvider() string {
	if x != nil {
		return x.AuthProvider
	}
	return ""
}

func (x *CreateProfileResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateProfileResponse) GetStatus() ProfileStatus {
	if x != nil {
		return x.Status
	}
	return ProfileStatus_PROFILE_STATUS_UNSPECIFIED
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_profile_v1_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_proto_rawDescGZIP(), []int{2}
}

func (x *GetProfileRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetProfileRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AuthProvider  string                 `protobuf:"bytes,4,opt,name=auth_provider,json=authProvider,proto3" json:"auth_provider,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Status        ProfileStatus          `protobuf:"varint,6,opt,name=status,proto3,enum=profile.v1.ProfileStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_profile_v1_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_proto_rawDescGZIP(), []int{3}
}

func (x *GetProfileResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetProfileResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetProfileResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *GetProfileResponse) GetAuthProvider() string {
	if x != nil {
		return x.AuthProvider
	}
	return ""
}

func (x *GetProfileResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetProfileResponse) GetStatus() ProfileStatus {
	if x != nil {
		return x.Status
	}
	return ProfileStatus_PROFILE_STATUS_UNSPECIFIED
}

var File_profile_v1_profile_proto protoreflect.FileDescriptor

const file_profile_v1_profile_proto_rawDesc = "" +
	"\n" +
	"\x18profile/v1/profile.proto\x12\n" +
	"profile.v1\x1a\x1bbuf/validate/validate.proto\"\xf8\x01\n" +
	"\x14CreateProfileRequest\x12%\n" +
	"\busername\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x03\x18 R\busername\x12\x1d\n" +
	"\x05email\x18\x02 \x01(\tB\a\xbaH\x04r\x02`\x01R\x05email\x12#\n" +
	"\bpassword\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\bR\bpassword\x12*\n" +
	"\fdisplay_name\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vdisplayName\x12,\n" +
	"\rauth_provider\x18\x05 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\fauthProvider\x12\x1b\n" +
	"\x04type\x18\x06 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04type\"\xd8\x01\n" +
	"\x15CreateProfileResponse\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12#\n" +
	"\rauth_provider\x18\x04 \x01(\tR\fauthProvider\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x121\n" +
	"\x06status\x18\x06 \x01(\x0e2\x19.profile.v1.ProfileStatusR\x06status\"\xbb\x01\n" +
	"\x11GetProfileRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email:t\xbaHq\x1ao\n" +
	"\x1ausername_or_email_required\x12(either username or email must be present\x1a'this.username != '' || this.email != ''\"\xd5\x01\n" +
	"\x12GetProfileResponse\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12#\n" +
	"\rauth_provider\x18\x04 \x01(\tR\fauthProvider\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x121\n" +
	"\x06status\x18\x06 \x01(\x0e2\x19.profile.v1.ProfileStatusR\x06status*\x85\x01\n" +
	"\rProfileStatus\x12\x1e\n" +
	"\x1aPROFILE_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PROFILE_STATUS_ACTIVE\x10\x01\x12\x1b\n" +
	"\x17PROFILE_STATUS_INACTIVE\x10\x02\x12\x1c\n" +
	"\x18PROFILE_STATUS_SUSPENDED\x10\x032\xb3\x01\n" +
	"\x0eProfileService\x12T\n" +
	"\rCreateProfile\x12 .profile.v1.CreateProfileRequest\x1a!.profile.v1.CreateProfileResponse\x12K\n" +
	"\n" +
	"GetProfile\x12\x1d.profile.v1.GetProfileRequest\x1a\x1e.profile.v1.GetProfileResponseB<Z:github.com/auroban/gochat-be/profile-service/proto;profileb\x06proto3"

var (
	file_profile_v1_profile_proto_rawDescOnce sync.Once
	file_profile_v1_profile_proto_rawDescData []byte
)

func file_profile_v1_profile_proto_rawDescGZIP() []byte {
	file_profile_v1_profile_proto_rawDescOnce.Do(func() {
		file_profile_v1_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_profile_v1_profile_proto_rawDesc), len(file_profile_v1_profile_proto_rawDesc)))
	})
	return file_profile_v1_profile_proto_rawDescData
}

var file_profile_v1_profile_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_profile_v1_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_profile_v1_profile_proto_goTypes = []any{
	(ProfileStatus)(0),            // 0: profile.v1.ProfileStatus
	(*CreateProfileRequest)(nil),  // 1: profile.v1.CreateProfileRequest
	(*CreateProfileResponse)(nil), // 2: profile.v1.CreateProfileResponse
	(*GetProfileRequest)(nil),     // 3: profile.v1.GetProfileRequest
	(*GetProfileResponse)(nil),    // 4: profile.v1.GetProfileResponse
}
var file_profile_v1_profile_proto_depIdxs = []int32{
	0, // 0: profile.v1.CreateProfileResponse.status:type_name -> profile.v1.ProfileStatus
	0, // 1: profile.v1.GetProfileResponse.status:type_name -> profile.v1.ProfileStatus
	1, // 2: profile.v1.ProfileService.CreateProfile:input_type -> profile.v1.CreateProfileRequest
	3, // 3: profile.v1.ProfileService.GetProfile:input_type -> profile.v1.GetProfileRequest
	2, // 4: profile.v1.ProfileService.CreateProfile:output_type -> profile.v1.CreateProfileResponse
	4, // 5: profile.v1.ProfileService.GetProfile:output_type -> profile.v1.GetProfileResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_profile_v1_profile_proto_init() }
func file_profile_v1_profile_proto_init() {
	if File_profile_v1_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_profile_v1_profile_proto_rawDesc), len(file_profile_v1_profile_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_profile_v1_profile_proto_goTypes,
		DependencyIndexes: file_profile_v1_profile_proto_depIdxs,
		EnumInfos:         file_profile_v1_profile_proto_enumTypes,
		MessageInfos:      file_profile_v1_profile_proto_msgTypes,
	}.Build()
	File_profile_v1_profile_proto = out.File
	file_profile_v1_profile_proto_goTypes = nil
	file_profile_v1_profile_proto_depIdxs = nil
}
